/**
 * Renderer Abstraction Layer
 * Converts engine-independent SceneGraph representations into target engine script payloads
 * for Unreal Engine 5 Python API / Commandlets or Blender bpy.
 */

import { SceneGraph } from "./sceneGraph.js";

export interface RenderAdapterResult {
    engine: 'unreal' | 'blender';
    scriptPayload: string;
    projectConfigPath?: string;
    executableArgs: string[];
    metadata: {
        totalNodesProcessed: number;
        hasVolumetricFog: boolean;
        hasLumenGI: boolean;
        hasNaniteMeshes: boolean;
    };
}

export interface RendererAdapter {
    getEngineName(): 'unreal' | 'blender';
    convertSceneGraph(sceneGraph: SceneGraph, outputFileName?: string): RenderAdapterResult;
}

export class UnrealAdapter implements RendererAdapter {
    getEngineName(): 'unreal' | 'blender' {
        return 'unreal';
    }

    convertSceneGraph(sceneGraph: SceneGraph, outputFileName: string = "unreal_frame.png"): RenderAdapterResult {
        const stats = sceneGraph.getStats();
        const env = sceneGraph.environment;
        const fog = env.volumetricFog;
        const postProcess = env.postProcess;

        // Generate engine-agnostic to Unreal Python API script
        let pyScript = `
# Unreal Engine 5 Automated Scene Assembly & Render Script
# Generated by Autonomous Swarm Engine Adapter (Renderer Abstraction Layer)

import unreal
import os

print("[UnrealAdapter] Assembling level from SceneGraph: '${sceneGraph.name}'")

# 1. Setup World & Editor Subsystems
editor_subsystem = unreal.get_editor_subsystem(unreal.UnrealEditorSubsystem)
level_subsystem = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
world = editor_subsystem.get_game_world()

# 2. Configure Volumetric Fog & Atmospheric Lighting
print("[UnrealAdapter] Enabling ExponentialHeightFog (Volumetric Fog = ${fog.enabled})")
fog_actor = unreal.EditorLevelLibrary.spawn_actor_from_class(unreal.ExponentialHeightFog, unreal.Vector(0,0,0))
if fog_actor:
    fog_comp = fog_actor.get_component_by_class(unreal.ExponentialHeightFogComponent)
    if fog_comp:
        fog_comp.set_editor_property("bEnableVolumetricFog", ${fog.enabled ? 'True' : 'False'})
        fog_comp.set_editor_property("volumetric_fog_scattering_distribution", 0.85)
        fog_comp.set_editor_property("volumetric_fog_extinction_scale", ${fog.extinctionScale})

# 3. Configure Lumen GI and Post Processing
print("[UnrealAdapter] Configuring PostProcessVolume (Lumen GI = ${postProcess.enableLumenGI}, Lumen Reflections = ${postProcess.enableLumenReflections})")
pp_actor = unreal.EditorLevelLibrary.spawn_actor_from_class(unreal.PostProcessVolume, unreal.Vector(0,0,0))
if pp_actor:
    pp_actor.set_editor_property("unbound", True)
    settings = pp_actor.get_editor_property("settings")
    settings.set_editor_property("dynamic_global_illumination_method", unreal.DynamicGlobalIlluminationMethod.LUMEN)
    settings.set_editor_property("reflection_method", unreal.ReflectionMethod.LUMEN)
    settings.set_editor_property("bloom_intensity", ${postProcess.bloomIntensity})

# 4. Construct Scene Graph Nodes (${stats.totalNodes} Nodes)
`;

        for (const node of sceneGraph.nodes.values()) {
            const pos = node.transform.position;
            const rot = node.transform.rotation;
            const sca = node.transform.scale;

            if (node.mesh) {
                const naniteFlag = node.mesh.enableNanite ?? true;
                pyScript += `
# Node: ${node.name} (Mesh: ${node.mesh.primitiveType || 'custom'}, Nanite: ${naniteFlag})
mesh_actor = unreal.EditorLevelLibrary.spawn_actor_from_class(unreal.StaticMeshActor, unreal.Vector(${pos.x * 100}, ${pos.y * 100}, ${pos.z * 100}))
if mesh_actor:
    mesh_actor.set_actor_label("${node.name}")
    mesh_actor.set_actor_rotation(unreal.Rotator(${rot.x}, ${rot.y}, ${rot.z}), False)
    mesh_actor.set_actor_scale_3d(unreal.Vector(${sca.x}, ${sca.y}, ${sca.z}))
`;
            }

            if (node.light) {
                pyScript += `
# Node: ${node.name} (Light: ${node.light.type}, Intensity: ${node.light.intensity})
light_actor = unreal.EditorLevelLibrary.spawn_actor_from_class(unreal.DirectionalLight, unreal.Vector(${pos.x * 100}, ${pos.y * 100}, ${pos.z * 100}))
if light_actor:
    light_actor.set_actor_label("${node.name}")
    light_comp = light_actor.get_component_by_class(unreal.LightComponent)
    if light_comp:
        light_comp.set_intensity(${node.light.intensity})
        light_comp.set_volumetric_scattering_intensity(${node.light.volumetricScatteringIntensity || 1.5})
`;
            }
        }

        pyScript += `
print("[UnrealAdapter] Scene graph conversion complete. Executing Movie Render Queue execution payload...")
`;

        return {
            engine: 'unreal',
            scriptPayload: pyScript,
            executableArgs: ["-executePythonScript", "-unattended", "-NullRHI"],
            metadata: {
                totalNodesProcessed: stats.totalNodes,
                hasVolumetricFog: fog.enabled,
                hasLumenGI: postProcess.enableLumenGI,
                hasNaniteMeshes: true
            }
        };
    }
}

export class BlenderAdapter implements RendererAdapter {
    getEngineName(): 'unreal' | 'blender' {
        return 'blender';
    }

    convertSceneGraph(sceneGraph: SceneGraph, outputFileName: string = "blender_frame.png"): RenderAdapterResult {
        const stats = sceneGraph.getStats();
        const env = sceneGraph.environment;
        const fog = env.volumetricFog;

        let pyScript = `import bpy
import math

print("[BlenderAdapter] Constructing scene '${sceneGraph.name}' from SceneGraph abstraction...")

# Clear existing objects
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)

# Setup Environment & Fog Volume
scene = bpy.context.scene
scene.render.engine = 'CYCLES'
world = scene.world || bpy.data.worlds.new("World")
scene.world = world
world.use_nodes = True

`;

        for (const node of sceneGraph.nodes.values()) {
            const pos = node.transform.position;
            const rot = node.transform.rotation;
            const sca = node.transform.scale;

            if (node.mesh) {
                if (node.mesh.primitiveType === 'cylinder') {
                    pyScript += `bpy.ops.mesh.primitive_cylinder_add(radius=1.0, depth=2.0, location=(${pos.x}, ${pos.y}, ${pos.z}))\n`;
                } else if (node.mesh.primitiveType === 'sphere') {
                    pyScript += `bpy.ops.mesh.primitive_uv_sphere_add(radius=1.0, location=(${pos.x}, ${pos.y}, ${pos.z}))\n`;
                } else {
                    pyScript += `bpy.ops.mesh.primitive_cube_add(size=2.0, location=(${pos.x}, ${pos.y}, ${pos.z}))\n`;
                }
                pyScript += `obj = bpy.context.active_object\nobj.name = "${node.name}"\nobj.scale = (${sca.x}, ${sca.y}, ${sca.z})\nobj.rotation_euler = (math.radians(${rot.x}), math.radians(${rot.y}), math.radians(${rot.z}))\n`;
            }

            if (node.light) {
                pyScript += `
bpy.ops.object.light_add(type='SUN', location=(${pos.x}, ${pos.y}, ${pos.z}))
sun = bpy.context.active_object
sun.data.energy = ${node.light.intensity / 1000}
`;
            }

            if (node.camera) {
                pyScript += `
bpy.ops.object.camera_add(location=(${pos.x}, ${pos.y}, ${pos.z}), rotation=(math.radians(${rot.x}), math.radians(${rot.y}), math.radians(${rot.z})))
cam = bpy.context.active_object
scene.camera = cam
`;
            }
        }

        pyScript += `
print("[BlenderAdapter] Scene assembly complete.")
`;

        return {
            engine: 'blender',
            scriptPayload: pyScript,
            executableArgs: ["--background", "--python"],
            metadata: {
                totalNodesProcessed: stats.totalNodes,
                hasVolumetricFog: fog.enabled,
                hasLumenGI: false,
                hasNaniteMeshes: false
            }
        };
    }
}
